
name: Python application

on:
  push:
    branches:  "main"


jobs:

  build:

    runs-on: ubuntu-latest

    outputs:
      package_version: ${{ steps.package_version.outputs.version }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true

    - name: Install Dependencies
      run: poetry install

    - name: Package Version
      id: package_version
      run: echo "version=$(poetry version -s)" >> "$GITHUB_OUTPUT"


  release:

    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{jobs.build.outputs.package_version}}
          release_name: Release v${{jobs.build.outputs.package_version}}
          draft: false
          prerelease: false
